apiVersion: kibana.k8s.elastic.co/v1beta1
kind: Kibana
metadata:
  name: kibana-efk
  namespace: logging
spec:
  version: 7.14.0
  count: 1
  elasticsearchRef:
    name: eck
  http:
    tls:
      selfSignedCertificate:
        disabled: true
