apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fuel-core
  namespace: <your-fuel-core-namespace>
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      app: fuel-core
  endpoints:
  - path: /metrics 
    port: http