{
 "title": "Beta 3 API metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests Response Time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(le) (increase(graphql_request_duration_seconds_bucket{path=\"request\", service=\"sentry-1-lb-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dry Run Response Time",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(le) (increase(graphql_request_duration_seconds_bucket{path=\"dryRun\", service=\"sentry-1-lb-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints call frequency per container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(graphql_request_duration_seconds_count{namespace=\"beta3\", service=\"sentry-1-lb-service\", path!=\"request\"}[1m])",
     "legendFormat": "{{container}}:{{path}}"
    }
   ]
  },
  {
   "title": "Total endpoints call frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(path) (rate(graphql_request_duration_seconds_count{namespace=\"beta3\", service=\"sentry-1-lb-service\", path!=\"request\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total endpoints requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(path) (rate(graphql_request_duration_seconds_count{namespace=\"beta3\", service=\"sentry-1-lb-service\", path=\"request\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}