apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: fuel-core-cpu-hpa
  namespace: fuel-core
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fuel-core-k8s 
  targetCPUUtilizationPercentage: 75