name: Testing CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:    
      - 'preview/**'

jobs:
  #  TEST
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      

       
        
      
